before:
  - description: Pull down and Configure the variables for our Singularity Deployment
    commands:
       - git clone git@git.hubteam.com:HubSpot/SingularityBuildConfig.git custom-build-config
       - /bin/bash custom-build-config/setup-ui-env.sh

after:
  onSuccess:
    - description:
      commands:
        - /bin/bash custom-build-config/publish-ui.sh

